name = "observeos-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "observeos"
database_id = "192f7e63-92f8-42e2-b6a6-5c93e9be9c47"

[vars]
ENVIRONMENT = "production"

# Set this as a secret: wrangler secret put API_KEY_SECRET
